# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-12 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodeads', '0008_auto_20161218_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culeba',
            name='cloud',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='culeba',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='culeba',
            name='lon',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='culeba',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='culeba',
            name='pressure',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='culeba',
            name='wind',
            field=models.FloatField(),
        ),
    ]
